"use strict";
/*

Function Declaration:
function SandwichMaker(breadType: string, fillingType: string): string

This line declares a function named SandwichMaker
that takes two parameters (breadType and fillingType), both of type string,
and returns a string.

*/
function SandwichMaker(breadType, fillingType) {
    /*
    
    Following line of code is responsible for constructing a string that describes
    the sandwich being made based on the inputs provided (breadType and fillingType). Let's dissect it step by step:
    
    "A ": This is a string literal that represents
    the beginning of the sandwich description. It says "A ".
    
    + breadType +: Here, breadType is a variable holding
    the type of bread for the sandwich (e.g., "wheat").
    
    The + operator is used for string concatenation, meaning
    it joins the contents of the variables and strings together.
    So, "A " + breadType effectively combines "A " with the specified type of bread.
    
    " sandwich with ": Another string literal that denotes
    the middle part of the sandwich description, saying " sandwich with ".
    
    + fillingType: Similar to breadType, fillingType is a variable holding
    the type of filling for the sandwich (e.g., "cheese").
    Again, the + operator concatenates this with the existing string.
    
    So, when you put it all together, this line of code constructs
    a string that describes the sandwich.
    For example, if breadType is "wheat" and fillingType is "cheese",
    the resulting sandwich variable will hold the string
    "A wheat sandwich with cheese".
    
    Function Body:
    The body of the function performs the steps to make a sandwich based on
    the provided inputs.
    
    */
    let sandwich = "A " + breadType + " sandwich with " + fillingType;
    /*
    Return Value: The function returns a string describing the prepared sandwich,
    which is then assigned to the variable mySandwich.
    */
    return sandwich;
}
// Example usage of the function
let mySandwich = SandwichMaker("wheat", "cheese");
/*
Function Call: let mySandwich = SandwichMaker("wheat", "cheese");
This line calls the SandwichMaker function
with the specified arguments
("wheat" for breadType and "cheese" for fillingType).
*/
console.log(mySandwich); // Output: The result is printed 
//to the console using console.log(mySandwich);.
//  ======= OUT PUT:    A wheat sandwich with cheese    =============
/*
This output is generated by the console.log(mySandwich); statement, which prints
the value returned by the SandwichMaker function.
In this case, the function returns the string "A wheat sandwich with cheese",
indicating the type of sandwich made based on the input parameters provided
("wheat" for the bread type and "cheese" for the filling type).
*/
// GIVING QUANTITY:
function SandwichMakerA(breadType, fillingType, breadQuantity, fillingQuantity) {
    let sandwich = "A " + breadQuantity + " slices of " + breadType + " sandwich with " + fillingQuantity + " slices of " + fillingType;
    return sandwich;
}
// Example usage of the function
let mySandwichA = SandwichMakerA("wheat", "cheese", 2, 3);
console.log(mySandwichA);
